services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Common\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Common\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

  App\Users\:
    resource: '../../src/'

  App\Users\UI\:
    resource: '../../src/UI/'
    tags: ['controller.service_arguments']