services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Common\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Common\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
    App\Common\Event\EventHandler:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

  App\SharedKernel\Language\:
    resource: '../../src/'
