doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            # users
            Users_UserId: App\Users\Infrastructure\Persistence\Doctrine\CustomTypes\UserIdType

            # sharedKernel/language
            Language_LanguageId: App\SharedKernel\Language\Infrastructure\Persistence\Doctrine\CustomTypes\LanguageIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Users\Domain:
                is_bundle: false
                type: xml
                prefix: 'App\Users\Domain'
                dir: '%kernel.project_dir%/src/Users/src/Infrastructure/Persistence/Doctrine/Mapping'
            App\SharedKernel\Language\Domain:
                is_bundle: false
                type: xml
                prefix: 'App\SharedKernel\Language\Domain'
                dir: '%kernel.project_dir%/src/SharedKernel/Language/src/Infrastructure/Persistence/Doctrine/Mapping'
